### ISSUE TITLE
Cpu usage is sometimes negative

### ISSUE THREAD

**Issue by AllanFly120** [soyuka/pidusage#69] opened 2018-07-11 07:25 UTC
Hi, I'm using pidusage to measure the CPU usage of a non-node process. But I find the usage sometimes returns negative value. How is this possible?

Thank you

*node version: 8.8.1*
*platform: macOS 10.12.6*
*library version: 2.0.11*

**Comment by simonepri** [comment] 2018-07-14 09:56
Hi @soyuka,
#36b96fa is not a fix, is just a workaround.

The problem is in `etime - hst.etime`
https://github.com/soyuka/pidusage/blob/master/lib/ps.js#L106
It seems that the etime var never gets put in the history.

**Comment by jupe** [comment] 2018-07-17 11:09
would like to get fix for this also

**Comment by chqy24** [comment] 2018-08-05 23:38
still get negative value, why multiply by 600 at https://github.com/soyuka/pidusage/blob/master/lib/ps.js#L14
IMO, It should be 
```
time += parseInt(tpart[i--], 10) * 10
```

**Comment by soyuka** [comment] 2018-08-06 06:04
hi @chqy24 what's your OS?

**Comment by jrgm** [comment] 2018-08-21 01:13
I also don't grok why the multiplier there is 600 (for the PLATFORM === 'darwin' case).

If I call `parseTime('17:52.00', true)` I get 1072000.
If I call `parseTime('17:51.50', true)` I get 1101000, which is greater than the value for `17:52:00`.

**Comment by soyuka** [comment] 2018-08-21 07:35
@jrgm would you be able to patch this? Thanks!

**Comment by simonepri** [comment] 2018-08-21 14:46
@jrgm I coded it, it's just a distraction error.
'17:51.50' means 17 minutes 51 seconds and 50 centiseconds
So yeah the multiplier should be 10

**Closed** 2018-08-22 07:02 UTC
Labels: bug
